'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ClinicSettings

    '''<summary>
    '''chkClinicTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkClinicTypes As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''ddlUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUsers As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRoles As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkMainDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMainDashboard As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDashboard As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPatients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPatients As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkNewPatients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNewPatients As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowPatients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowPatients As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnVisits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVisits As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnLast5Visits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLast5Visits As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnTreatmentPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTreatmentPlan As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAttachments As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnEditPatient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditPatient As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnExportExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportExcel As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnExportPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportPDF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPatientsPayments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPatientsPayments As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPatientPaymentsReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPatientPaymentsReport As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPatientsDebtsSubscriptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPatientsDebtsSubscriptions As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDaily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDaily As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOpenTreatmentCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpenTreatmentCard As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDashboardAppointments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDashboardAppointments As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAppointments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAppointments As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDoctors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDoctors As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAddDoctor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddDoctor As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkShowAllDoctor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowAllDoctor As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnEditDoctor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditDoctor As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnToggleDoctor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToggleDoctor As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDoctorSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDoctorSchedule As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDoctorReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDoctorReports As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkInsurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInsurance As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAddInsuranceCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddInsuranceCompany As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAddInsuranceCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddInsuranceCard As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkInsuranceReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInsuranceReports As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAccounts As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSuppliers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSuppliers As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSuppliersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSuppliersList As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnEditSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditSupplier As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnViewInvoices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewInvoices As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEmployees As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEmployeesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEmployeesList As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnEditEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditEmployee As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnViewWithdrawals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnViewWithdrawals As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWithdrawals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWithdrawals As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAddExpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddExpense As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAddPurchaseInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddPurchaseInvoice As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkFinancialReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFinancialReports As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDebtsReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDebtsReports As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSettings As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTreatmentsManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTreatmentsManager As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnAddGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddGroup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnAddTreatment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddTreatment As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnEditGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditGroup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnEditTreatment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditTreatment As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnDeleteGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteGroup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnDeleteTreatment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteTreatment As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkClinicSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkClinicSettings As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPersonalPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPersonalPage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSubscriptionPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSubscriptionPayment As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkContactUs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkContactUs As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSaveSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveSettings As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSettings As Global.System.Web.UI.WebControls.Button
End Class
