'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MedicalReport

    '''<summary>
    '''txtExamDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExamDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlDoctor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDoctor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPatient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPatient As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''patientSuggestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents patientSuggestions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''patientAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents patientAge As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnPatientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPatientID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtMedicalReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMedicalReport As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMedicine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMedicine As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''medicineSuggestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents medicineSuggestions As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtMedicineCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMedicineCount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMedicineNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMedicineNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMedicinesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMedicinesList As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdnMedicinesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMedicinesList As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlPaymentMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPaymentMethod As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPaidAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPaidAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdnTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTotal As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnPaidAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPaidAmount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''fuAttachments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuAttachments As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnEditPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditPlan As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnNewPaidAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnNewPaidAmount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnInsuranceCompanyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnInsuranceCompanyID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnInsuranceCardID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnInsuranceCardID As Global.System.Web.UI.WebControls.HiddenField
End Class
