'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site1

    '''<summary>
    '''lnkTopLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTopLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDashboard As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkPatients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPatients As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkNewPatients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNewPatients As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkShowPatients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowPatients As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkPatientsPayments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPatientsPayments As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkPatientPaymentsReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPatientPaymentsReport As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkPatientsDebtsSubscriptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPatientsDebtsSubscriptions As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkDaily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDaily As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkOpenTreatmentCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpenTreatmentCard As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkDashboardAppointments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDashboardAppointments As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkAppointments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAppointments As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkDoctors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDoctors As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkAddDoctor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddDoctor As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkShowAllDoctor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowAllDoctor As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkDoctorSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDoctorSchedule As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkDoctorReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDoctorReports As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkInsurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInsurance As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkAddInsuranceCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddInsuranceCompany As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkAddInsuranceCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddInsuranceCard As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkInsuranceReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInsuranceReports As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkAccounts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAccounts As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkSuppliers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSuppliers As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkSuppliersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSuppliersList As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEmployees As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkEmployeesList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEmployeesList As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkWithdrawals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWithdrawals As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkAddExpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddExpense As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkAddPurchaseInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddPurchaseInvoice As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkFinancialReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFinancialReports As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkDebtsReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDebtsReports As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSettings As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkTreatmentsManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTreatmentsManager As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkClinicSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkClinicSettings As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkPersonalPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPersonalPage As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkSubscriptionPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSubscriptionPayment As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''chkContactUs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkContactUs As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ChangeUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChangeUser As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnkLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
